AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Go Lambda for SAM Local

Globals:
  Function:
    Timeout: 10

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-world
      Runtime: go1.x
      CodeUri: cmd/
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get
