version: "3.9"

networks:
  sam-local:   # ← SAM からもこのネットワークに参加させる
    external: true

services:
  db:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command:
      - "-jar"
      - "DynamoDBLocal.jar"
      - "-sharedDb"
    networks:
      - sam-local