// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dipendency_injection

import (
	"encoding/json"
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"hello-world/adapter/handler/Badge/get"
	upsert2 "hello-world/adapter/handler/Badge/upsert"
	get3 "hello-world/adapter/handler/BadgeAward/get"
	upsert4 "hello-world/adapter/handler/BadgeAward/upsert"
	get2 "hello-world/adapter/handler/BadgeRank/get"
	upsert3 "hello-world/adapter/handler/BadgeRank/upsert"
	get4 "hello-world/adapter/handler/PublishAward/get"
	get5 "hello-world/adapter/handler/SubscribeAward/get"
	"hello-world/adapter/handler/User/get"
	upsert5 "hello-world/adapter/handler/User/upsert"
	"hello-world/domain/management"
	"hello-world/infra/lambda"
	"net/http"
)

// Injectors from wire.go:

func InitializeRouter() (*chi.Mux, error) {
	handler := get.NewBadgeHandler()
	badgeGetController := NewBadgeGetController(handler)
	upsertHandler := upsert.NewUserHandler()
	userGetController := NewUserGetController(upsertHandler)
	getHandler := get2.NewBadgeRankHandler()
	badgeRankGetController := NewBadgeRankGetController(getHandler)
	handler2 := get3.NewBadgeAwardHandler()
	badgeAwardGetController := NewBadgeAwardGetController(handler2)
	handler3 := get4.NewPublisherHandler()
	publishAwardGetController := NewPublishAwardGetController(handler3)
	subscriptionHandler := get5.NewSubscriptionHandler()
	subscribeAwardGetController := NewSubscribeAwardGetController(subscriptionHandler)
	getController := NewGetController(badgeGetController, userGetController, badgeRankGetController, badgeAwardGetController, publishAwardGetController, subscribeAwardGetController)
	handler4 := upsert2.NewBadgeHandler()
	badgePostController := NewBadgePostController(handler4)
	handler5 := upsert3.NewBadgeRankHandler()
	badgeRankPostController := NewBadgeRankPostController(handler5)
	handler6 := upsert4.NewBadgeAwardHandler()
	badgeAwardPostController := NewBadgeAwardPostController(handler6)
	handler7 := upsert5.NewUserHandler()
	userPostController := NewUserPostController(handler7)
	postController := NewPostController(badgePostController, badgeRankPostController, badgeAwardPostController, userPostController)
	mux := lambda.NewRouter(getController, postController)
	return mux, nil
}

// wire.go:

var Set = wire.NewSet(upsert.NewUserHandler, upsert5.NewUserHandler, get3.NewBadgeAwardHandler, upsert4.NewBadgeAwardHandler, get2.NewBadgeRankHandler, upsert3.NewBadgeRankHandler, get4.NewPublisherHandler, get5.NewSubscriptionHandler, get.NewBadgeHandler, upsert2.NewBadgeHandler, NewBadgeGetController, NewUserGetController, NewSubscribeAwardGetController, NewPublishAwardGetController, NewBadgeRankGetController, NewBadgeAwardGetController,
	NewBadgePostController, NewBadgeRankPostController, NewBadgeAwardPostController, NewUserPostController,
	NewGetController, NewPostController, lambda.NewRouter,
)

type BadgeGetController struct{ BadgeGet get.Handler }

func NewBadgeGetController(
	badgeGet *get.Handler,
) *BadgeGetController {
	return &BadgeGetController{BadgeGet: *badgeGet}
}

func (c *BadgeGetController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	id := r.URL.Query().Get("id")
	value, err := c.BadgeGet.Do(ctx, id)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	writeJSON(w, http.StatusOK, value)

}

/**
* GET Method
 */
// UserGetController ユーザー情報を取得する
type UserGetController struct{ UserGet upsert.Handler }

func NewUserGetController(
	userGet *upsert.Handler,
) *UserGetController {
	return &UserGetController{UserGet: *userGet}
}

func (c *UserGetController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	id := r.URL.Query().Get("id")
	value, err := c.UserGet.Do(ctx, id)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	writeJSON(w, http.StatusOK, value)

}

// BadgeAwardGetController 成果通知(バッチ付与・更新)する対象者を抽出する
type BadgeAwardGetController struct{ BadgeAwardGet get3.Handler }

func NewBadgeAwardGetController(
	badgeAwardGet *get3.Handler,
) *BadgeAwardGetController {
	return &BadgeAwardGetController{BadgeAwardGet: *badgeAwardGet}
}

func (c *BadgeAwardGetController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	value, err := c.BadgeAwardGet.Do(ctx)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	writeJSON(w, http.StatusOK, value)

}

// BadgeRankGetController 指定したIDのバッチRank情報を取得する
type BadgeRankGetController struct{ BadgeRankGet get2.Handler }

func NewBadgeRankGetController(
	badgeRankGet *get2.Handler,
) *BadgeRankGetController {
	return &BadgeRankGetController{BadgeRankGet: *badgeRankGet}
}

func (c *BadgeRankGetController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	id := r.URL.Query().Get("id")
	value, err := c.BadgeRankGet.Do(ctx, id)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	writeJSON(w, http.StatusOK, value)

}

// PublishAwardGetController 生活うち対象のユーザーを抽出し通知対象者としてキューにパブリッシュする
type PublishAwardGetController struct {
	PublishAwardGet get4.Handler
}

func NewPublishAwardGetController(
	publishAwardGet *get4.Handler,
) *PublishAwardGetController {
	return &PublishAwardGetController{PublishAwardGet: *publishAwardGet}
}

func (c *PublishAwardGetController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	err := c.PublishAwardGet.Do(ctx)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	writeJSON(w, http.StatusOK, "success")

}

// PublishAwardGetController 配信したいユーザー情報をキューに入れておく
type SubscribeAwardGetController struct {
	SubscribeAwardGet get5.SubscriptionHandler
}

func NewSubscribeAwardGetController(
	subscribeAwardGet *get5.SubscriptionHandler,
) *SubscribeAwardGetController {
	return &SubscribeAwardGetController{SubscribeAwardGet: *subscribeAwardGet}
}

func (c *SubscribeAwardGetController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	value, err := c.SubscribeAwardGet.Do(ctx)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	writeJSON(w, http.StatusOK, value)

}

/**
* POST Method
 */
type UserPostController struct{ UserPost upsert5.Handler }

func NewUserPostController(userPost *upsert5.Handler) *UserPostController {
	return &UserPostController{
		UserPost: *userPost,
	}
}

func (c *UserPostController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	var userDTO management.UserDTO

	if err := json.NewDecoder(r.Body).Decode(&userDTO); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	value, err := c.UserPost.Do(ctx, userDTO)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, value)
}

type BadgeAwardPostController struct{ BadgeAwardPost upsert4.Handler }

func NewBadgeAwardPostController(badgeAwardPost *upsert4.Handler) *BadgeAwardPostController {
	return &BadgeAwardPostController{
		BadgeAwardPost: *badgeAwardPost,
	}
}

func (c *BadgeAwardPostController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	var userBadgeAwardDTO management.UserBadgeAwardDTO

	if err := json.NewDecoder(r.Body).Decode(&userBadgeAwardDTO); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	userBadgeAward, err := management.NewUserBadgeAward(userBadgeAwardDTO.UserBadgeAwardID, userBadgeAwardDTO.UserID, userBadgeAwardDTO.BadgeRankID)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	value, err := c.BadgeAwardPost.Do(ctx, *userBadgeAward)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, value)
}

type BadgeRankPostController struct{ BadgeRankPost upsert3.Handler }

func NewBadgeRankPostController(badgeRankPost *upsert3.Handler) *BadgeRankPostController {
	return &BadgeRankPostController{BadgeRankPost: *badgeRankPost}
}

func (c *BadgeRankPostController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	var badgeDetailsByRankDTO management.BadgeDetailsByRankDTO

	if err := json.NewDecoder(r.Body).Decode(&badgeDetailsByRankDTO); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	userBadgeAward, err := management.NewBadgeDetailsByRank(
		badgeDetailsByRankDTO.BadgeRankID,
		badgeDetailsByRankDTO.BadgeName,
		badgeDetailsByRankDTO.Message,
		badgeDetailsByRankDTO.Effect,
		badgeDetailsByRankDTO.Reason,
		badgeDetailsByRankDTO.Rank,
	)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	value, err := c.BadgeRankPost.Do(ctx, *userBadgeAward)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, value)
}

type BadgePostController struct{ BadgePost upsert2.Handler }

func NewBadgePostController(badgePost *upsert2.Handler) *BadgePostController {
	return &BadgePostController{
		BadgePost: *badgePost,
	}
}

func (c *BadgePostController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	var badgeDTO management.BadgeDTO

	if err := json.NewDecoder(r.Body).Decode(&badgeDTO); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	badge, err := management.NewBadge(badgeDTO.ID, badgeDTO.Name, badgeDTO.Reason)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	value, err := c.BadgePost.Do(ctx, *badge)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, value)
}

type GetController struct {
	BadgeGetController          *BadgeGetController
	UserGetController           *UserGetController
	BadgeRankGetController      *BadgeRankGetController
	BadgeAwardGetController     *BadgeAwardGetController
	PublishAwardGetController   *PublishAwardGetController
	SubscribeAwardGetController *SubscribeAwardGetController
}

func NewGetController(
	badgeGetController *BadgeGetController,
	userGetController *UserGetController,
	badgeRankGetController *BadgeRankGetController,
	badgeAwardGetController *BadgeAwardGetController,
	publishAwardGetController *PublishAwardGetController,
	subscribeAwardGetController *SubscribeAwardGetController) lambda.GetController {
	return &GetController{
		BadgeGetController:          badgeGetController,
		UserGetController:           userGetController,
		BadgeRankGetController:      badgeRankGetController,
		BadgeAwardGetController:     badgeAwardGetController,
		PublishAwardGetController:   publishAwardGetController,
		SubscribeAwardGetController: subscribeAwardGetController,
	}
}

func (g GetController) GetController() map[string]http.Handler {
	getController := map[string]http.Handler{}
	getController["/badge"] = g.BadgeGetController
	getController["/user"] = g.UserGetController
	getController["/rank"] = g.BadgeRankGetController
	getController["/award"] = g.BadgeAwardGetController
	getController["/publish"] = g.PublishAwardGetController
	getController["/subscribe"] = g.SubscribeAwardGetController
	return getController
}

type PostController struct {
	BadgePostController      *BadgePostController
	BadgeRankPostController  *BadgeRankPostController
	BadgeAwardPostController *BadgeAwardPostController
	UserPostController       *UserPostController
}

func NewPostController(
	badgePostController *BadgePostController,
	badgeRankPostController *BadgeRankPostController,
	badgeAwardPostController *BadgeAwardPostController,
	userPostController *UserPostController) lambda.PostController {
	return &PostController{
		BadgePostController:      badgePostController,
		BadgeRankPostController:  badgeRankPostController,
		BadgeAwardPostController: badgeAwardPostController,
		UserPostController:       userPostController,
	}
}

func (p PostController) PostController() map[string]http.Handler {
	postController := map[string]http.Handler{}
	postController["/badge"] = p.BadgePostController
	postController["/rank"] = p.BadgeRankPostController
	postController["/award"] = p.BadgeAwardPostController
	postController["/user"] = p.UserPostController
	return postController
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}
