// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dipendency_injection

import (
	"encoding/json"
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"hello-world/adapter/handler/Badge/get"
	"hello-world/infra/lambda"
	"net/http"
)

// Injectors from wire.go:

func InitializeRouter() (*chi.Mux, error) {
	getController := NewGetController()
	postController := NewPostController()
	mux := lambda.NewRouter(getController, postController)
	return mux, nil
}

// wire.go:

var Set = wire.NewSet(get.NewBadgeHandler, NewGetController, NewPostController, lambda.NewRouter)

type BadgeGetController struct{ BadgeGet get.Handler }

func NewBadgeGetController() *BadgeGetController {
	return &BadgeGetController{}
}

func (c *BadgeGetController) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	id := r.URL.Query().Get("id")
	value, err := c.BadgeGet.Do(ctx, id)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"val": err.Error()})
	}
	writeJSON(w, http.StatusOK, value)

}

type GetController struct{}

func NewGetController() lambda.GetController {
	return &GetController{}
}

func (g GetController) GetController() map[string]http.Handler {
	getController := map[string]http.Handler{}
	getController["/badge"] = NewBadgeGetController()
	return getController
}

type PostController struct{}

func NewPostController() lambda.PostController {
	return &PostController{}
}

func (p PostController) PostController() map[string]http.Handler {
	postController := map[string]http.Handler{}
	return postController
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}
