### GET request to example server
GET http://localhost:3000/hello

### GET proxy path
GET http://localhost:3000/proxy/varify

#### GET health path
GET http://localhost:3000/health

#### GET health path
GET http://localhost:3000/health/proxy

### POST user

POST http://localhost:1323/
Content-Type: application/json

{
  "name": "haruki",
  "mail": "hogehoge@gmail.com"
}